id: P008200
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG09751
  title: ཉི་ཧོང་ཆོས་འབྱུང་ཕྱོགས་བསྡུས་
  author: ''
  volumes:
    3c17b243bee043f88767e4686b741a34:
      image_group_id: I00KG09833
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
