id: I8483FF30
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:26:22+00:00'
last_modified: '2022-06-09T05:11:47.201734+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09751
  title: ཉི་ཧོང་ཆོས་འབྱུང་ཕྱོགས་བསྡུས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DCEC:
      image_group_id: I00KG09833
      title: ''
      total_pages: 166
      order: 1
      base_file: DCEC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
